version: "3.9"
services:
  db:
    image: postgres:15
    container_name: bewise_db
    volumes:
      - db_data:/var/lib/postgresql/data

    env_file:
      - .env.prod
  app:
    build:
      context: .
    env_file:
      - .env.prod
    container_name: bewise_app
    command: ["/Bewise/app.sh"]
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  db_data: